### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ArnyminerZ** [ArnyminerZ/icsx5#1]
Here's the general roadmap for the rewrite of ICSx⁵, it will be for sure updated during the development process, and individual issues will be created from this one.

- [x] Project structure:
    - [x] #3
        _See [Android docs](https://developer.android.com/build/migrate-to-kotlin-dsl)_
    - [x] #4
    - [x] #5
        _Even if they have breaking changes, the new app should be using the last version of all the libraries._
    - [x] #10
- [x] Check whether anything broke and document it (create issues)
  - [x] #23
  - [x] Can we still create, edit and delete subscriptions?
  - [x] Set sync interval ?
  - [x] #25
- [x] Migrate to Jetpack Compose (**no theming!**, we do that with compose theming engine later)
    - [x] #39
        - [X] #12
          - [x] #34
            - [x] #24
          - [x] #28
          - [x] #30
    - [x] #49
      - [x] #50
        - [x] #41
    - [x] #53
    - [x] Migrate all standard flavor Fragments to Jetpack Compose
      - [x] #74
- [x] #86
- [x] #47
- [x] #100
- [x] #97
- [x] #105
- [x] #107
---

After speaking with Ricki I believe it would be good for us to bring ArnyminerZ/ICSx5 in a usable state now and merge it back into [bitfireAT/icsx5](https://github.com/bitfireAT/icsx5). The following issues/PRs are mainly features and can be merged seperately into the main repo later on.

- [ ] clear subscription error message at appropriate moment
- [ ] Improve non-ui features
- [x] Update AGP
- [ ] #71
      Ideally, if in the first step (`AddCalendarEnterUrlFragment`), the Activity should be left; but if in the `AddCalendarDetailsFragment`, the navigation should be moved to the previous Fragment instead.
      *Will be fixed on #37*
- [ ] #69
- [ ] #76
- [x] #98
- [ ] #73
- [ ] #104 
- [ ] Allow focusing different fields of the forms using the "next" arrow in the keyboard.
        See [KeyboardActions](https://developer.android.com/reference/kotlin/androidx/compose/foundation/text/KeyboardActions)
